In [1]:
import pandas as pd
import numpy as np

In [2]:
df_original = pd.read_csv("spotify_dataset.csv") # Reading the actual dataset csv file
df = df_original.copy()

In [3]:
df_original.info()
df_original.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26173514 entries, 0 to 26173513
Data columns (total 9 columns):
 #   Column   Dtype
---  ------   -----
 0   title    object
 1   rank     int64
 2   date     object
 3   artist   object
 4   url      object
 5   region   object
 6   chart    object
 7   trend    object
 8   streams  float64
dtypes: float64(1), int64(1), object(7)
memory usage: 1.8+ GB

,title,rank,date,artist,url,region,chart,trend,streams
0,Chantaje (feat. Maluma),1,2017-01-01,Shakira,https://open.spotify.com/track/6mICuAdrwEjh6Y6...,Argentina,top200,SAME_POSITION,253019.0
1,Vente Pa' Ca (feat. Maluma),2,2017-01-01,Ricky Martin,https://open.spotify.com/track/7DM4BPaS7uofFul...,Argentina,top200,MOVE_UP,223988.0
2,Reggaetón Lento (Bailemos),3,2017-01-01,CNCO,https://open.spotify.com/track/3AEZUABDXNtecAO...,Argentina,top200,MOVE_DOWN,210943.0
3,Safari,4,2017-01-01,"J Balvin, Pharrell Williams, BIA, Sky",https://open.spotify.com/track/6rQSrBHf7HlZjtc...,Argentina,top200,SAME_POSITION,173865.0
4,Shaky Shaky,5,2017-01-01,Daddy Yankee,https://open.spotify.com/track/58IL315gMSTD37D...,Argentina,top200,MOVE_UP,153956.0
5,Traicionera,6,2017-01-01,Sebastian Yatra,https://open.spotify.com/track/5J1c3M4EldCfNxX...,Argentina,top200,MOVE_DOWN,151140.0
6,Cuando Se Pone a Bailar,7,2017-01-01,Rombai,https://open.spotify.com/track/1MpKZi1zTXpERKw...,Argentina,top200,MOVE_DOWN,148369.0
7,Otra vez (feat. J Balvin),8,2017-01-01,Zion & Lennox,https://open.spotify.com/track/3QwBODjSEzelZyV...,Argentina,top200,MOVE_DOWN,143004.0
8,La Bicicleta,9,2017-01-01,"Carlos Vives, Shakira",https://open.spotify.com/track/0sXvAOmXgjR2QUq...,Argentina,top200,MOVE_UP,126389.0
9,Dile Que Tu Me Quieres,10,2017-01-01,Ozuna,https://open.spotify.com/track/20ZAJdsKB5IGbGj...,Argentina,top200,MOVE_DOWN,112012.0

In [4]:
df = df[df.chart == 'top200']
# Modifying the dataset to have only the top200 chart and disassociate the viral50 chart

In [5]:
df = df.drop(['url','chart','trend'], axis=1)
# Droppping the url, chart and trend attribute columns. These attributes have no purpose in our case and increase size of the dataset.

In [6]:
df = df[df['date'].str[-2:]=='01']
# Filtering rows with date '01' as we do not wish to consider all days and looking to bring down the size of dataset

In [7]:
df = df[df['date'].str[:4] != '2017']
df = df[df['date'].str[:4] != '2018']
# Excluding records related to years 2017 and 2018 to decrease size of the dataset

In [8]:
df['date'] = pd.to_datetime(df['date'], format='%Y-%m-%d')
# Changing the data type of the 'date' attribute to datetime64[ns]

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 431590 entries, 19128 to 22324800
Data columns (total 6 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   title    431590 non-null  object
 1   rank     431590 non-null  int64
 2   date     431590 non-null  datetime64[ns]
 3   artist   431590 non-null  object
 4   region   431590 non-null  object
 5   streams  431590 non-null  float64
dtypes: datetime64[ns](1), float64(1), int64(1), object(3)
memory usage: 23.0+ MB

In [10]:
df.head(10)

           title  rank       date        artist    region  streams
19128    Ride It   146 2020-05-01        Regard   Bolivia   1956.0
19234     +Linda   147 2020-05-01         Dalex   Bolivia   1953.0
19287       Woah   148 2020-05-01      Lil Baby    Canada  35211.0
19390       25/8   105 2020-05-01     Bad Bunny     Chile  31854.0
19698       Keii    65 2020-05-01      Anuel AA  Colombia  16155.0
20166    Ride It    99 2020-05-01        Regard   Ecuador   5999.0
20427  Hei rakas    13 2020-05-01          BEHM   Finland  28838.0
28326     Tel Me   198 2020-05-01    Jul, Ninho    France  33011.0
28645      GOOBA     9 2020-06-01       6ix9ine   Austria  22249.0
28799         P2    69 2020-05-01  Lil Uzi Vert    Latvia   1193.0

In [13]:
# Write data to a different CSV file. This will be used as the final dataset on which we will perform our analysis and visualisations
df.to_csv('transformed_dataset.csv', encoding='utf-8', index=False)